apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: mss
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
    nodePort: 32064
  selector:
    app: redis
    role: follower
    tier: backend
